# Generated by Django 4.0.3 on 2022-03-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=125, verbose_name='Nom du fournisseurs')),
                ('adresse', models.CharField(max_length=125, verbose_name='Adresse du fournissuer')),
                ('tel', models.CharField(max_length=125, verbose_name='Numéro de télephone')),
            ],
        ),
    ]
