# Generated by Django 4.0.3 on 2022-03-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='prix',
        ),
    ]
