# Generated by Django 4.0.3 on 2022-03-24 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_takingarticles_poste'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeding',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Prix Unitiare'),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding', to='stock.article', verbose_name='Article Entrant'),
        ),
    ]
