# Generated by Django 4.0.3 on 2022-03-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_feeding_prix_alter_feeding_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix Unitaire'),
        ),
    ]
