# Generated by Django 4.0.3 on 2022-03-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_article_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='single_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
