# Generated by Django 4.0.3 on 2022-03-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_taking_guiven_to_taking_poste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takingarticles',
            name='poste',
        ),
        migrations.AlterField(
            model_name='taking',
            name='poste',
            field=models.CharField(blank=True, choices=[('CAFE', 'CAFE'), ('RESTAURENT', 'RESTAURENT'), ('LAITERIE', 'LAITERIE'), ('GRILLADE', 'GRILLADE'), ('TAFERNOUTE', 'TAFERNOUTE'), ('SNACK', 'SNACK')], max_length=125, null=True, verbose_name='Prélévement pour quel Poste ?'),
        ),
    ]
