# Generated by Django 4.0.3 on 2022-08-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_taking_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.CharField(choices=[('Superette', 'Superette'), ('Global', 'Global'), ('Stock', 'Stock'), ('Fruit et Légumes', 'Fruit et Légumes'), ('Viandes et Volailles', 'Viandes et Volailles'), ('Poissons', 'Poissons'), ('Epices', 'Epices'), ('Boissons Chaudes', 'Boissons Chaudes'), ('Boissons Fraiches', 'Boissons Fraiches'), ('Pains', 'Pains'), ('Epiceries et Conserves', 'Epiceries et Conserves'), ('Huiles et Vinaigres', 'Huiles et Vinaigres'), ('Consomables cuisines', 'Consomables cuisines'), ('Fournitures cafe et resto', 'Fournitures cafe et resto'), ('Produits et Patisseries', 'Produits et Patisseries'), ('BOF', 'BOF'), ('Produits Ménage', 'Produits Ménage'), ('Frait transport', 'Frait transport'), ('Fourniture Bureau', 'Fourniture Bureau'), ('Divers', 'Divers')], max_length=125, verbose_name='Classification'),
        ),
        migrations.AlterField(
            model_name='taking',
            name='poste',
            field=models.CharField(blank=True, choices=[('CAFE', 'CAFE'), ('RESTAURENT', 'RESTAURENT'), ('LAITERIE', 'LAITERIE'), ('GRILLADE', 'GRILLADE'), ('TAFERNOUTE', 'TAFERNOUTE'), ('SNACK', 'SNACK'), ('Superette', 'Superette')], max_length=125, null=True, verbose_name='Prélévement pour quel Poste ?'),
        ),
    ]
