# Generated by Django 4.0.3 on 2022-09-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_alter_article_group_alter_taking_poste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='fed_on',
            new_name='date_feed',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='article',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='qté',
        ),
        migrations.RemoveField(
            model_name='feeding',
            name='ref',
        ),
        migrations.AddField(
            model_name='feeding',
            name='br',
            field=models.CharField(max_length=125, null=True, verbose_name='Bon de réception N°'),
        ),
        migrations.AddField(
            model_name='feeding',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taking_fourni', to='stock.fournisseur', verbose_name='Fournisseur'),
        ),
        migrations.AddField(
            model_name='feeding',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='FeedingArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.article')),
                ('feeding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_entrant', to='stock.feeding')),
            ],
        ),
    ]
